name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      #- uses: actions/setup-python@v2
      #  with:
      #    python-version: '3.8'
      - name: unittest
        uses: onichandame/python-test-action@master
        with:
          path: './test' 
